# Generated by Django 5.1.6 on 2025-03-21 05:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='description',
        ),
        migrations.AddField(
            model_name='brand',
            name='address',
            field=models.TextField(default='No address provided', verbose_name='Business Address'),
        ),
        migrations.AddField(
            model_name='brand',
            name='phone',
            field=models.CharField(default='0000000000', max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit phone number.', regex='^[6789]\\d{9}$')], verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='brand',
            name='representative_name',
            field=models.CharField(default='Unknown Representative', max_length=100, verbose_name='Representative Name'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='brand_name',
            field=models.CharField(default='Unknown Brand', max_length=100, verbose_name='Brand Name'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(default='default_logo.png', upload_to='brand_logos/', verbose_name='Brand Logo'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='customer_photos/', verbose_name='Profile Photo'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Pincode must be 6 digits.', regex='^\\d{6}$')], verbose_name='Pincode'),
        ),
        migrations.AlterField(
            model_name='login',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='login',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Is Approved'),
        ),
        migrations.AlterField(
            model_name='login',
            name='usertype',
            field=models.CharField(choices=[('admin', 'Admin'), ('brand', 'Brand'), ('customer', 'Customer')], default='customer', max_length=20, verbose_name='User Type'),
        ),
    ]
