# Generated by Django 5.1.6 on 2025-03-23 06:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_alter_brand_options_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='pincode',
            field=models.CharField(blank=True, max_length=6, null=True, validators=[django.core.validators.RegexValidator(message='Pincode must be 6 digits.', regex='^\\d{6}$')], verbose_name='Pincode'),
        ),
    ]
