# Generated by Django 5.1.6 on 2025-04-06 05:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_brand_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='aadhaar_photo',
            field=models.ImageField(blank=True, null=True, upload_to='aadhaar_photos/', verbose_name='Aadhaar Card Photo'),
        ),
        migrations.AddField(
            model_name='brand',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='Bank Account Number'),
        ),
        migrations.AddField(
            model_name='brand',
            name='gstin',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid GSTIN number', regex='^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9A-Z]{1}Z[0-9A-Z]{1}$')], verbose_name='GSTIN'),
        ),
        migrations.AddField(
            model_name='brand',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid IFSC code (format: ABCD0123456)', regex='^[A-Z]{4}0[A-Z0-9]{6}$')], verbose_name='IFSC Code'),
        ),
        migrations.AddField(
            model_name='brand',
            name='pan_card',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid PAN card number (format: ABCDE1234F)', regex='^[A-Z]{5}[0-9]{4}[A-Z]{1}$')], verbose_name='PAN Card Number'),
        ),
    ]
