# Generated by Django 5.1.6 on 2025-03-25 06:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authapp', '0004_brand_pincode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(upload_to='products/')),
                ('feature_vector', models.BinaryField(blank=True, null=True)),
                ('size_type', models.CharField(choices=[('alphabet', 'Alphabetic Sizes'), ('numeric', 'Numeric Sizes')], default='alphabet', max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('material', models.TextField(blank=True, null=True)),
                ('product_code', models.CharField(max_length=100, unique=True)),
                ('package_contains', models.CharField(blank=True, max_length=255, null=True)),
                ('marketed_by', models.TextField(blank=True, null=True)),
                ('imported_by', models.TextField(blank=True, null=True)),
                ('country_of_origin', models.CharField(blank=True, max_length=100, null=True)),
                ('net_quantity', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_care_address', models.TextField(blank=True, null=True)),
                ('commodity', models.CharField(blank=True, max_length=255, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authapp.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerceapp.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_type', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('28', '28'), ('30', '30'), ('32', '32'), ('34', '34'), ('36', '36')], max_length=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='ecommerceapp.product')),
            ],
        ),
    ]
