# Generated by Django 5.1.6 on 2025-03-25 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0002_alter_product_product_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsize',
            name='stock',
        ),
        migrations.AddField(
            model_name='product',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
