# Generated by Django 5.1.6 on 2025-03-25 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0003_remove_productsize_stock_product_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_available',
            field=models.BooleanField(default=True),
        ),
    ]
