# Generated by Django 5.1.6 on 2025-03-27 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_brand_pincode'),
        ('ecommerceapp', '0005_cart_cartitem_cart_cart_must_have_login_or_session'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cart',
            name='cart_must_have_login_or_session',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='login',
        ),
        migrations.AddField(
            model_name='cart',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authapp.customer'),
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.CheckConstraint(condition=models.Q(('customer__isnull', False), ('session_id__isnull', False), _connector='OR'), name='cart_must_have_customer_or_session'),
        ),
    ]
