# Generated by Django 5.1.6 on 2025-03-27 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0006_remove_cart_cart_must_have_login_or_session_and_more'),
    ]

    operations = [
    ]
