# Generated by Django 5.1.6 on 2025-03-27 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0007_recreate_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='Uncheck to hide the product from customers.'),
        ),
    ]
