# Generated by Django 5.1.6 on 2025-03-28 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0011_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='stripe_payment_intent_id',
        ),
    ]
