# Generated by Django 5.1.6 on 2025-04-04 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0013_order_razorpay_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='razorpay_order_id',
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Net Banking', 'Net Banking'), ('Credit/Debit card', 'Credit/Debit Card'), ('cod', 'Cash on Delivery')], max_length=20),
        ),
    ]
